# Copyright (c) Meta Platforms, Inc. and affiliates.
# All rights reserved.
#
# This source code is licensed under the license found in the
# LICENSE file in the root directory of this source tree.

"""LoRA fine-tuning with elderly voice augmented training data.

Extends lora_train.py by adding augmented elderly-voice clips to the
training set. The augmented clips are generated by augment_elderly.py
and stored in DATAPATH/AugmentedElderly/.

Only training data is augmented — validation stays clean to measure
real-world performance.

Usage:
    DATAPATH=... SAVEPATH=... LORA_R=128 uv run python -m tribev2.emotion.lora_train_augmented
"""

import csv
import os
from pathlib import Path

from tribev2.emotion.lora_train import (  # noqa: F401
    BACKBONE_NAME,
    BATCH_SIZE,
    EMOTION_LABELS,
    EPOCHS,
    LR_HEAD,
    LR_LORA,
    LORA_ALPHA,
    LORA_DROPOUT,
    LORA_LAYERS,
    LORA_R,
    LORA_TARGET_MODULES,
    MAX_AUDIO_SEC,
    NUM_CLASSES,
    PATIENCE,
    SAMPLE_RATE,
    WARMUP_STEPS,
    EmotionAudioDataset,
    LoRAEmotionModel,
    build_model,
    evaluate,
    train_one_epoch,
)
import tribev2.emotion.lora_train as _base

# Override save dir
SAVEDIR = os.path.join(
    os.getenv("SAVEPATH", "/home/didierlacroix1/data/emotion_save"),
    "results", f"tribe_emotion_lora_augmented_r{LORA_R}",
)
Path(SAVEDIR).mkdir(parents=True, exist_ok=True)
_base.SAVEDIR = SAVEDIR

# Lower LR for fine-tuning from pre-trained weights
_base.LR_LORA = 1e-5   # 5x lower than initial training
_base.LR_HEAD = 1e-4    # 5x lower than initial training
_base.EPOCHS = 20       # fewer epochs needed for fine-tuning
_base.PATIENCE = 8


def load_clips() -> tuple[list[dict], list[dict]]:
    """Load original + augmented training clips, clean validation."""
    from tribev2.studies.emotion_audio import CremadEmotion, RavdessEmotion

    datapath = Path(os.getenv("DATAPATH", "/home/didierlacroix1/data/emotion"))
    train_clips, val_clips = [], []

    # Original RAVDESS + CREMA-D
    for StudyClass, subdir in [
        (RavdessEmotion, "RavdessEmotion"),
        (CremadEmotion, "CremadEmotion"),
    ]:
        study = StudyClass(path=datapath / subdir)
        for tl in study.iter_timelines():
            events = study._load_timeline_events(tl)
            split = events.iloc[0].get("split", "train")
            filepath = events.iloc[0]["filepath"]
            clip = {"filepath": filepath, "emotion": tl["emotion"], "split": split}
            (val_clips if split == "val" else train_clips).append(clip)

    orig_train = len(train_clips)

    # Add augmented elderly clips (training only)
    aug_meta = datapath / "AugmentedElderly" / "metadata.csv"
    if aug_meta.exists():
        with open(aug_meta) as f:
            reader = csv.DictReader(f)
            for row in reader:
                if Path(row["filepath"]).exists():
                    train_clips.append({
                        "filepath": row["filepath"],
                        "emotion": row["emotion"],
                        "split": "train",
                    })

    import logging
    logger = logging.getLogger(__name__)
    logger.info(
        "Training clips: %d original + %d augmented = %d total",
        orig_train, len(train_clips) - orig_train, len(train_clips),
    )
    logger.info("Validation clips: %d (clean, no augmentation)", len(val_clips))

    return train_clips, val_clips


_base.load_clips = load_clips


if __name__ == "__main__":
    _base.main()
